name: Build Windows Executable

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Locate tkinterdnd2 and customtkinter paths
        id: paths
        run: |
          echo "TKDND_PATH=$(python -c "import tkinterdnd2, os; print(os.path.dirname(tkinterdnd2.__file__))")" >> $env:GITHUB_ENV
          echo "CTK_PATH=$(python -c "import customtkinter, os; print(os.path.dirname(customtkinter.__file__))")" >> $env:GITHUB_ENV

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --noconfirm --onedir --windowed ^
          --icon "assets/images/logo.ico" ^
          --add-data "$env:TKDND_PATH;tkinterdnd2/" ^
          --add-data "$env:CTK_PATH;customtkinter/" ^
          drag_app.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows-executable
          path: dist/
