name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Download and setup tkdnd
      run: |
        $tkdndVersion = "2.9.3"
        $tkdndUrl = "https://github.com/petasis/tkdnd/releases/download/$tkdndVersion/tkdnd-$tkdndVersion.tar.gz"
        Invoke-WebRequest -Uri $tkdndUrl -OutFile "tkdnd.tar.gz"
        tar -xzf tkdnd.tar.gz
        
    - name: Build with PyInstaller
      run: |
        $env:TCL_LIBRARY = (python -c "import tcl; print(tcl.__path__[0])")
        $env:TK_LIBRARY = (python -c "import tkinter; print(tkinter.__path__[0])")
        pyinstaller --noconfirm --onefile --windowed --name "FilesManager" `
          --add-data "src;src" `
          --add-data "tkdnd2.9.3/lib/tkdnd2.9.3;tkdnd2.9.3" `
          --hidden-import "tkinter" `
          --hidden-import "customtkinter" `
          --hidden-import "tkinterdnd2" `
          src/main.py
        
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: FilesManager-Windows
        path: dist/FilesManager.exe
