name: Build Windows Executable

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build with PyInstaller
      shell: cmd
      run: |
        pyinstaller --noconfirm --onedir --windowed ^
        --icon "assets/images/logo.ico" ^
        --add-data "venv/Lib/site-packages/tkinterdnd2;tkinterdnd2/" ^
        --add-data "venv/Lib/site-packages/customtkinter;customtkinter/" ^
        src/main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: files_manager-exe
        path: ${{ env.TEMP }}\dist
