name: Build Windows Executable

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Get package paths
      id: paths
      shell: cmd
      run: |
        for /f "delims=" %%i in ('python -c "import tkinterdnd2; print(tkinterdnd2.__path__[0])"') do set PYTHONPATH_TKDND2=%%i
        for /f "delims=" %%i in ('python -c "import customtkinter; print(customtkinter.__path__[0])"') do set PYTHONPATH_CTK=%%i
        echo Paths set

    - name: Build with PyInstaller
      shell: cmd
      run: |
        pyinstaller --noconfirm --onedir --windowed ^
        --icon "assets/images/logo.ico" ^
        --add-data "%PYTHONPATH_TKDND2%;tkinterdnd2" ^
        --add-data "%PYTHONPATH_CTK%;customtkinter" ^
        src/main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: files_manager-exe
        path: dist/
