name: Build Windows Executable

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install customtkinter tkinterdnd2 pyinstaller

      - name: Copy customtkinter and tkinterdnd2 from site-packages
        run: |
          $site_packages = (python -c "import site; print(site.getsitepackages()[0])")
          Copy-Item "$site_packages\customtkinter" -Destination "$env:GITHUB_WORKSPACE\customtkinter" -Recurse
          Copy-Item "$site_packages\tkinterdnd2" -Destination "$env:GITHUB_WORKSPACE\tkinterdnd2" -Recurse

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --noconfirm --onedir --windowed `
            --icon "src/assets/images/logo.ico" `
            --add-data "customtkinter;customtkinter" `
            --add-data "tkinterdnd2;tkinterdnd2" `
            --add-data "src/assets;src/assets" `
            src/main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: FilesManager
          path: dist/
