name: Build Windows Executable

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
      TKDND_PATH: ${{ runner.temp }}\\venv\\Lib\\site-packages\\tkinterdnd2
      CTK_PATH: ${{ runner.temp }}\\venv\\Lib\\site-packages\\customtkinter

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv venv
          venv\Scripts\activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable with PyInstaller
        run: |
          venv\Scripts\activate
          pyinstaller `
            --noconfirm `
            --onedir `
            --windowed `
            --icon "assets/images/logo.ico" `
            --add-data "$env:TKDND_PATH;tkinterdnd2/" `
            --add-data "$env:CTK_PATH;customtkinter/" `
            main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-executable
          path: dist/
