name: Build Windows Executable

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Get module paths
      id: module_paths
      run: |
        $tkdndPath = python -c "import tkinterdnd2; print(tkinterdnd2.__path__[0])"
        $ctkPath = python -c "import customtkinter; print(customtkinter.__path__[0])"
        echo "TKDND_PATH=$tkdndPath" >> $env:GITHUB_ENV
        echo "CTK_PATH=$ctkPath" >> $env:GITHUB_ENV

    - name: Build with PyInstaller
      run: |
        pyinstaller --noconfirm --onedir --windowed `
        --icon "assets/images/logo.ico" `
        --add-data "$env:TKDND_PATH;tkinterdnd2" `
        --add-data "$env:CTK_PATH;customtkinter" `
        src/main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: files_manager-exe
        path: dist/
